# Generated by Django 2.1.3 on 2018-11-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('extension', models.CharField(max_length=30)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
